### ISSUE TITLE
Incorrectly counting multiple nearby indels <50bp as FPs

### ISSUE THREAD

**Issue by jzook** [Sentieon/hap-eval#2]
In general, the matching is looking really promising, but I found an interesting issue with how hap-eval counts indels <50bp as FPs in some cases. In particular, we compared a vcf similar to the HPRC assembly-based vcf (https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/data/AshkenazimTrio/analysis/HPRC-HG002.cur.20211005/HPRC-cur.20211005-align2-GRCh37.dip.vcf.gz) to the GIAB v0.6 benchmark. It seems that if nearby indels <50bp add up to >=50bp (the default size threshold), then hap-eval counts them as FPs, even if they are on opposite haplotypes, as in GRCh37 chr1:7,394,284-7,396,084 below
<img width="1488" alt="Screen Shot 2022-11-08 at 8 54 47 PM" src="https://user-images.githubusercontent.com/2439798/200717593-06afc0ea-b987-4ef5-97a9-d93118f5bf51.png">

This perhaps is reasonable in some cases where the variants add up to >=50bp (or whatever threshold is set), like in the case below, though even here they don't seem to be part of the same tandem repeat so probably aren't related to each other, and would likely be better to exclude from FPs:
<img width="1496" alt="Screen Shot 2022-11-08 at 8 59 53 PM" src="https://user-images.githubusercontent.com/2439798/200718273-2648708c-0cec-41ef-b34e-1ddb4a85b32c.png">

My suggestion is to keep these when doing the comparisons but probably exclude them from the FP count, if you don't think that causes other big problems.

Thanks again for your great work on this!

**Comment by DonFreed** [comment]
Glad this is looking good!

We've added more accurate `--minsize` filtering in https://github.com/Sentieon/hap-eval/commit/606b20810669fe1da944ac3f4bd853165b3efb93. After this change, the variants in your first example are properly ignored (as both variant haplotypes are < `--minsize` compared to the reference).

Regarding the second example, `hap-eval` performs a clustering of variants in the VCFs before reassembly. Currently the clustering uses a fixed size of 1000bp by default (set with the `--maxdist` argument). 1000bp works well for relatively large events, but is probably too large for small events, like the variants in your second example.

As an improvement, we should implement some sort of adaptive `--maxdist` so that the chunk size is smaller for small events. Ideally this could allow for improved filtering of events < `--minsize` and could improve TP/FP/FN counting.

**Comment by DonFreed** [comment]
Closing this to track the adaptive clustering distance in #5.
